---

- name: elasticsearch - install on debian
  include: install_debian.yml
  when: ansible_os_family == "Debian"

- name: elasticsearch - install on centos
  include: install_centos.yml
  when: ansible_os_family == "RedHat"

- include: config.yml

- include: plugins.yml

- debug: var=elasticsearch_env

- name: elasticsearch - service
  include: service.yml
